// Code generated by MockGen. DO NOT EDIT.
// Source: keptn-contrib/job-executor-service/pkg/keptn (interfaces: UniformClient,LogEventSender)

// Package fake is a generated GoMock package.
package fake

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/keptn/go-utils/pkg/api/models"
	v2 "github.com/keptn/go-utils/pkg/api/utils/v2"
)

// MockUniformClient is a mock of UniformClient interface.
type MockUniformClient struct {
	ctrl     *gomock.Controller
	recorder *MockUniformClientMockRecorder
}

// MockUniformClientMockRecorder is the mock recorder for MockUniformClient.
type MockUniformClientMockRecorder struct {
	mock *MockUniformClient
}

// NewMockUniformClient creates a new mock instance.
func NewMockUniformClient(ctrl *gomock.Controller) *MockUniformClient {
	mock := &MockUniformClient{ctrl: ctrl}
	mock.recorder = &MockUniformClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUniformClient) EXPECT() *MockUniformClientMockRecorder {
	return m.recorder
}

// GetRegistrations mocks base method.
func (m *MockUniformClient) GetRegistrations(arg0 context.Context, arg1 v2.UniformGetRegistrationsOptions) ([]*models.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrations", arg0, arg1)
	ret0, _ := ret[0].([]*models.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrations indicates an expected call of GetRegistrations.
func (mr *MockUniformClientMockRecorder) GetRegistrations(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrations", reflect.TypeOf((*MockUniformClient)(nil).GetRegistrations), arg0, arg1)
}

// MockLogEventSender is a mock of LogEventSender interface.
type MockLogEventSender struct {
	ctrl     *gomock.Controller
	recorder *MockLogEventSenderMockRecorder
}

// MockLogEventSenderMockRecorder is the mock recorder for MockLogEventSender.
type MockLogEventSenderMockRecorder struct {
	mock *MockLogEventSender
}

// NewMockLogEventSender creates a new mock instance.
func NewMockLogEventSender(ctrl *gomock.Controller) *MockLogEventSender {
	mock := &MockLogEventSender{ctrl: ctrl}
	mock.recorder = &MockLogEventSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogEventSender) EXPECT() *MockLogEventSenderMockRecorder {
	return m.recorder
}

// Flush mocks base method.
func (m *MockLogEventSender) Flush(arg0 context.Context, arg1 v2.LogsFlushOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockLogEventSenderMockRecorder) Flush(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockLogEventSender)(nil).Flush), arg0, arg1)
}

// Log mocks base method.
func (m *MockLogEventSender) Log(arg0 []models.LogEntry, arg1 v2.LogsLogOptions) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", arg0, arg1)
}

// Log indicates an expected call of Log.
func (mr *MockLogEventSenderMockRecorder) Log(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockLogEventSender)(nil).Log), arg0, arg1)
}
