// Code generated by MockGen. DO NOT EDIT.
// Source: resource_service.go

// Package fake is a generated GoMock package.
package fake

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/keptn/go-utils/pkg/api/models"
	api "github.com/keptn/go-utils/pkg/api/utils"
)

// MockKeptnResourceHandler is a mock of KeptnResourceHandler interface.
type MockKeptnResourceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockKeptnResourceHandlerMockRecorder
}

// MockKeptnResourceHandlerMockRecorder is the mock recorder for MockKeptnResourceHandler.
type MockKeptnResourceHandlerMockRecorder struct {
	mock *MockKeptnResourceHandler
}

// NewMockKeptnResourceHandler creates a new mock instance.
func NewMockKeptnResourceHandler(ctrl *gomock.Controller) *MockKeptnResourceHandler {
	mock := &MockKeptnResourceHandler{ctrl: ctrl}
	mock.recorder = &MockKeptnResourceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeptnResourceHandler) EXPECT() *MockKeptnResourceHandlerMockRecorder {
	return m.recorder
}

// GetResource mocks base method.
func (m *MockKeptnResourceHandler) GetResource(scope api.ResourceScope, options ...api.URIOption) (*models.Resource, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{scope}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetResource", varargs...)
	ret0, _ := ret[0].(*models.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResource indicates an expected call of GetResource.
func (mr *MockKeptnResourceHandlerMockRecorder) GetResource(scope interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{scope}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResource", reflect.TypeOf((*MockKeptnResourceHandler)(nil).GetResource), varargs...)
}
