apiVersion: skaffold/v2beta23
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    # job executor service
    - image: keptncontrib/job-executor-service
      docker:
        dockerfile: Dockerfile
    # init container for actual jobs (will be used for every job that is started)
    - image: keptncontrib/job-executor-service-initcontainer
      docker:
        dockerfile: initcontainer.Dockerfile
# Before executing this, install job-executor-service manually:
# helm install -n keptn job-executor-service https://github.com/keptn-contrib/job-executor-service/releases/download/0.1.4/job-executor-service-0.1.4.tgz
deploy:
  helm:
    flags:
      install: [ "--create-namespace" ]
      upgrade: [ "--install", "--create-namespace", "--reuse-values"] # keep configuration (e.g., Keptn API Token)
    releases:
      - name: job-executor-service # needs to be the same name as currently used (check via helm ls -n keptn)
        namespace: keptn-jes # needs to be the same namespace as where the helm-chart is currently deployed
        # upgradeOnChange: true
        # recreatePods: false # don't recreate all pods
        artifactOverrides:
          image: keptncontrib/job-executor-service
          jobexecutorserviceinitcontainer:
            image: keptncontrib/job-executor-service-initcontainer
        imageStrategy:
          helm: { }
        setValueTemplates:
          remoteControlPlane:
            autoDetect:
              enabled: true       # If no auto-detection of Keptn should be done, set to false and fill out the information below
              namespace: ""       # For multiple Keptn version this should be set to the desired Keptn namespace
            api:
              protocol: ""
              hostname: ""
              token: ""
              authMode: "token"
              oauth:
                clientId: ""
                clientSecret: ""
                clientDiscovery: ""
                scopes: ""
          networkPolicy:
            ingress:
              enabled: true
            egress:
              enabled: false
              k8sMasterCIDR: ""
              k8sMasterPort: 0
        overrides:
          distributor:
            image:
              tag: 0.14.3
            securityContext:
              seccompProfile:
                type: Unconfined # needed for debugging
          resources:
            limits:
              memory: 512Mi # increase memory limit such that debugging using delve works
          securityContext:
            seccompProfile:
              type: Unconfined # needed for debugging
        chartPath: chart
