apiVersion: v2
actions:
  - name: Run locust
    events:
      - name: sh.keptn.event.test.triggered
        jsonpath:
          property: $.data.test.teststrategy
          match: locust
    tasks:
      - name: Run locust smoke tests
        files:
          - locust/basic.py
          - locust/import.py
        image: locustio/locust
        cmd:
          - locust
        args:
          - '-f'
          - /keptn/locust/basic.py
  - name: Run Bash
    events:
      - name: sh.keptn.event.action.triggered
        jsonpath:
          property: $.data.action.action
          match: hello
    tasks:
      - name: Run static world
        image: bash
        cmd:
          - echo
        args:
          - static
      - name: Run hello world
        files:
          - hello/hello-world.txt
        image: bash
        cmd:
          - cat
        args:
          - /keptn/hello/hello-world.txt
