############################################################################
# Build Container Images                                                   #
############################################################################
container_build:
  needs: [prepare_ci_run]
  strategy:
    matrix:
      component: [ "left-leg", "right-leg", "left-arm", "right-arm", "hats", "main" ]
      version: [ "v1", "v2", "v3", "v4" ]
  runs-on: ubuntu-20.04
  env:
    BRANCH: ${{ needs.prepare_ci_run.outputs.BRANCH }}
    VERSION: ${{ needs.prepare_ci_run.outputs.VERSION }}
    DATETIME: ${{ needs.prepare_ci_run.outputs.DATE }}${{ needs.prepare_ci_run.outputs.TIME }}
    GIT_SHA: ${{ needs.prepare_ci_run.outputs.GIT_SHA }}
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v1.0.0'

    - name: Login to GitHub Container Registry
      if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release-*' }}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}


    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
        working-directory: podtato-services/${{ matrix.component }}

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        build-args: |
          VERSION=${{ matrix.version }}
        context: podtato-services/${{ matrix.component }}/.
        push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release-*' }}
        file: podtato-services/${{ matrix.component }}/docker/Dockerfile
        platforms: linux/amd64
        tags: |
          ${{ env.CONTAINER_REGISTRY }}/podtato-head/podtato-${{ matrix.component }}:${{ matrix.version}}-latest-dev
          ${{ env.CONTAINER_REGISTRY }}/podtato-head/podtato-${{ matrix.component }}:${{ matrix.version}}-${{ env.VERSION }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.CONTAINER_REGISTRY }}/podtato-head/podtato-${{ matrix.component }}:${{ matrix.version}}-${{ env.VERSION }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: '${{ env.TRIVY_IGNORE_UNFIXED }}'
        vuln-type: '${{ env.TRIVY_VULN_TYPE }}'
        severity: '${{ env.TRIVY_SEVERITY }}'