apiVersion: v1
kind: ConfigMap
metadata:
  name: job-service-config
data:
  job_namespace: "{{ .Release.Namespace }}"
  init_container_image: "{{ .Values.jobexecutorserviceinitcontainer.image.repository }}:{{ .Values.jobexecutorserviceinitcontainer.image.tag | default .Chart.AppVersion }}"
  default_resource_limits_cpu: "1"
  default_resource_limits_memory: "512Mi"
  default_resource_requests_cpu: "50m"
  default_resource_requests_memory: "128Mi"
  always_send_finished_event: "false"
  enable_kubernetes_api_access: "{{ .Values.jobConfig.enableKubernetesApiAccess | default false }}"
---
# Secret for the Keptn API Token
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: job-serivce-keptn-secrets
data:
  token: {{ .Values.remoteControlPlane.api.token | b64enc | quote }}
  endpoint: {{ (printf "%s://%s/api" .Values.remoteControlPlane.api.protocol .Values.remoteControlPlane.api.hostname) | b64enc }}
  configuration-endpoint: {{ (printf "%s://%s/api/configuration-service" .Values.remoteControlPlane.api.protocol .Values.remoteControlPlane.api.hostname) | b64enc }}