apiVersion: v1
kind: ConfigMap
metadata:
  name: job-service-config
data:
  job_namespace: "{{ .Release.Namespace }}"
  init_container_image: "{{ .Values.jobexecutorserviceinitcontainer.image.repository }}:{{ .Values.jobexecutorserviceinitcontainer.image.tag | default .Chart.AppVersion }}"
  default_resource_limits_cpu: "1"
  default_resource_limits_memory: "512Mi"
  default_resource_requests_cpu: "50m"
  default_resource_requests_memory: "128Mi"
  always_send_finished_event: "false"
  keptn_api_endpoint: {{ include "job-executor-service.remote-control-plane.endpoint" . }}
  init_container_configuration_endpoint: {{ include "job-executor-service.remote-control-plane.configuration-endpoint" . }}
  default_job_service_account: "{{ include "job-executor-service.jobConfig.serviceAccountName" . }}"
  allow_privileged_jobs: "{{ .Values.jobConfig.allowPrivilegedJobs | default "false" }}"
  additional_job_labels: |
    {{- with .Values.jobConfig.labels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  task_deadline_seconds: {{ .Values.jobConfig.taskDeadlineSeconds | default 0 | quote}}
