{{- if ((.Values.jobConfig).serviceAccount).create | default true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "job-executor-service.jobConfig.serviceAccountName" . }}
  labels:
    {{- include "job-executor-service.labels" . | nindent 4 }}
  {{- with ((.Values.jobConfig).serviceAccount).annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
# Role for the jobs
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-executor-service_job
  namespace: {{ .Release.Namespace }}
rules: []
---
# Bind role for accessing secrets onto the job service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-executor-service_job
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-executor-service_job
subjects:
  - kind: ServiceAccount
    name: {{ include "job-executor-service.jobConfig.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}