apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: job-service-keptn-secrets
  namespace: {{ .Release.Namespace }}
data:
  token: {{ b64enc (include "job-executor-service.remote-control-plane.token" .) | quote }}