apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: job-service-keptn-secrets
data:
  token: {{ b64enc (include "job-executor-service.remote-control-plane.token" .) | quote }}
  oauth_client_secret: {{ b64enc (.Values.remoteControlPlane.api.oauth.clientSecret | default "") | quote }}
