apiVersion: v1
kind: ConfigMap
metadata:
  name: job-service-config
data:
  job_namespace: "{{ .Release.Namespace }}"
  init_container_image: "{{ .Values.jobexecutorserviceinitcontainer.image.repository }}:{{ .Values.jobexecutorserviceinitcontainer.image.tag | default .Chart.AppVersion }}"
