// Code generated by MockGen. DO NOT EDIT.
// Source: keptn-contrib/job-executor-service/pkg/eventhandler (interfaces: ImageFilter,EventMapper,JobConfigReader)

// Package fake is a generated GoMock package.
package fake

import (
	config "keptn-contrib/job-executor-service/pkg/config"
	reflect "reflect"

	event "github.com/cloudevents/sdk-go/v2/event"
	gomock "github.com/golang/mock/gomock"
)

// MockImageFilter is a mock of ImageFilter interface.
type MockImageFilter struct {
	ctrl     *gomock.Controller
	recorder *MockImageFilterMockRecorder
}

// MockImageFilterMockRecorder is the mock recorder for MockImageFilter.
type MockImageFilterMockRecorder struct {
	mock *MockImageFilter
}

// NewMockImageFilter creates a new mock instance.
func NewMockImageFilter(ctrl *gomock.Controller) *MockImageFilter {
	mock := &MockImageFilter{ctrl: ctrl}
	mock.recorder = &MockImageFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageFilter) EXPECT() *MockImageFilterMockRecorder {
	return m.recorder
}

// IsImageAllowed mocks base method.
func (m *MockImageFilter) IsImageAllowed(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsImageAllowed", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsImageAllowed indicates an expected call of IsImageAllowed.
func (mr *MockImageFilterMockRecorder) IsImageAllowed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsImageAllowed", reflect.TypeOf((*MockImageFilter)(nil).IsImageAllowed), arg0)
}

// MockEventMapper is a mock of EventMapper interface.
type MockEventMapper struct {
	ctrl     *gomock.Controller
	recorder *MockEventMapperMockRecorder
}

// MockEventMapperMockRecorder is the mock recorder for MockEventMapper.
type MockEventMapperMockRecorder struct {
	mock *MockEventMapper
}

// NewMockEventMapper creates a new mock instance.
func NewMockEventMapper(ctrl *gomock.Controller) *MockEventMapper {
	mock := &MockEventMapper{ctrl: ctrl}
	mock.recorder = &MockEventMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventMapper) EXPECT() *MockEventMapperMockRecorder {
	return m.recorder
}

// Map mocks base method.
func (m *MockEventMapper) Map(arg0 event.Event) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Map", arg0)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Map indicates an expected call of Map.
func (mr *MockEventMapperMockRecorder) Map(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Map", reflect.TypeOf((*MockEventMapper)(nil).Map), arg0)
}

// MockJobConfigReader is a mock of JobConfigReader interface.
type MockJobConfigReader struct {
	ctrl     *gomock.Controller
	recorder *MockJobConfigReaderMockRecorder
}

// MockJobConfigReaderMockRecorder is the mock recorder for MockJobConfigReader.
type MockJobConfigReaderMockRecorder struct {
	mock *MockJobConfigReader
}

// NewMockJobConfigReader creates a new mock instance.
func NewMockJobConfigReader(ctrl *gomock.Controller) *MockJobConfigReader {
	mock := &MockJobConfigReader{ctrl: ctrl}
	mock.recorder = &MockJobConfigReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobConfigReader) EXPECT() *MockJobConfigReaderMockRecorder {
	return m.recorder
}

// GetJobConfig mocks base method.
func (m *MockJobConfigReader) GetJobConfig() (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobConfig")
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobConfig indicates an expected call of GetJobConfig.
func (mr *MockJobConfigReaderMockRecorder) GetJobConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobConfig", reflect.TypeOf((*MockJobConfigReader)(nil).GetJobConfig))
}
