// Code generated by MockGen. DO NOT EDIT.
// Source: keptn-contrib/job-executor-service/pkg/config (interfaces: KeptnResourceService,JobConfigVerifier)

// Package fake is a generated GoMock package.
package fake

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockKeptnResourceService is a mock of KeptnResourceService interface.
type MockKeptnResourceService struct {
	ctrl     *gomock.Controller
	recorder *MockKeptnResourceServiceMockRecorder
}

// MockKeptnResourceServiceMockRecorder is the mock recorder for MockKeptnResourceService.
type MockKeptnResourceServiceMockRecorder struct {
	mock *MockKeptnResourceService
}

// NewMockKeptnResourceService creates a new mock instance.
func NewMockKeptnResourceService(ctrl *gomock.Controller) *MockKeptnResourceService {
	mock := &MockKeptnResourceService{ctrl: ctrl}
	mock.recorder = &MockKeptnResourceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeptnResourceService) EXPECT() *MockKeptnResourceServiceMockRecorder {
	return m.recorder
}

// GetKeptnResource mocks base method.
func (m *MockKeptnResourceService) GetKeptnResource(arg0 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeptnResource", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeptnResource indicates an expected call of GetKeptnResource.
func (mr *MockKeptnResourceServiceMockRecorder) GetKeptnResource(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeptnResource", reflect.TypeOf((*MockKeptnResourceService)(nil).GetKeptnResource), arg0)
}

// MockJobConfigVerifier is a mock of JobConfigVerifier interface.
type MockJobConfigVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockJobConfigVerifierMockRecorder
}

// MockJobConfigVerifierMockRecorder is the mock recorder for MockJobConfigVerifier.
type MockJobConfigVerifierMockRecorder struct {
	mock *MockJobConfigVerifier
}

// NewMockJobConfigVerifier creates a new mock instance.
func NewMockJobConfigVerifier(ctrl *gomock.Controller) *MockJobConfigVerifier {
	mock := &MockJobConfigVerifier{ctrl: ctrl}
	mock.recorder = &MockJobConfigVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobConfigVerifier) EXPECT() *MockJobConfigVerifierMockRecorder {
	return m.recorder
}

// VerifyJobConfig mocks base method.
func (m *MockJobConfigVerifier) VerifyJobConfig(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyJobConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyJobConfig indicates an expected call of VerifyJobConfig.
func (mr *MockJobConfigVerifierMockRecorder) VerifyJobConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyJobConfig", reflect.TypeOf((*MockJobConfigVerifier)(nil).VerifyJobConfig), arg0)
}
